import { useEffect, useState } from 'react';
import { BookOpen, Check, CheckCheck, Download, ExternalLink, History, Link2, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { api, messageOf } from '../../api';
import type { CircleDetail, CircleOutcome, CircleSearchItem, CircleSource } from '../../../shared/circles-types';
import { OutcomeEditor } from './CircleForms';
import { circlePath, Citations, CircleModal, ConfirmDialog, dateTime, EmptyState, ErrorNote, isAbort, Loading, Notice, safeUrl, scopeNames, scopeNotes, SubmitButton, useTask, type Notify } from './CirclesCommon';

export function CircleSources({ circle, writable, onChanged, notify }: { circle: CircleDetail; writable: boolean; onChanged: () => void; notify: Notify }) {
  const [adding, setAdding] = useState(false), [searchOpen, setSearchOpen] = useState(false), [removing, setRemoving] = useState<CircleSource | null>(null);
  const [query, setQuery] = useState((circle.rounds.find(round => round.id === circle.selectedRoundId)?.question || '').slice(0, 200));
  const [items, setItems] = useState<CircleSearchItem[]>([]), [searched, setSearched] = useState(false), [searchedQuery, setSearchedQuery] = useState(''), [notice, setNotice] = useState<string | null>(null), [added, setAdded] = useState<Set<string>>(new Set());
  const searchTask = useTask(), addTask = useTask();
  return <section className="cz-resources" aria-label="本轮资料"><div className="cz-panel-heading"><div><h2>让讨论有据可循</h2><p>区分链接、原文片段和搜索摘要，保留出处供成员核实。</p></div>{writable && <button className="cz-button cz-primary cz-small" onClick={() => setAdding(true)}><Plus size={15}/>添加资料</button>}</div>
    {writable && <div className="cz-source-search"><button className="cz-text-button" onClick={() => setSearchOpen(value => !value)} aria-expanded={searchOpen}><Search size={16}/>{searchOpen ? '收起知乎资料搜索' : '搜索知乎资料'}</button>{searchOpen && <><p className="cz-muted">点击搜索时才查询知乎，返回的摘要不会被标记为全文。</p><form className="cz-search-form" onSubmit={event => { event.preventDefault(); const term = query.trim(); if (term.length < 2) return; searchTask.run(() => api<{ items: CircleSearchItem[]; notice: string | null }>(`${circlePath(circle.id)}/search?q=${encodeURIComponent(term)}`), result => { setItems(result.items); setNotice(result.notice); setSearched(true); setSearchedQuery(term); }); }}><div className="cz-search-input"><Search size={17}/><input aria-label="知乎资料关键词" value={query} onChange={event => setQuery(event.target.value)} minLength={2} maxLength={200} required disabled={searchTask.busy}/></div><button className="cz-button" type="submit" disabled={searchTask.busy}>{searchTask.busy ? '搜索中…' : '查询知乎'}</button></form><ErrorNote text={searchTask.error}/>{notice && <Notice><p>{notice}</p></Notice>}{searched && <div className="cz-search-results"><p className="cz-muted">“{searchedQuery}” 的搜索结果</p>{!items.length && <p>暂无相关搜索结果，可以补充关键词或手动添加资料。</p>}{items.map(item => <article key={item.searchResultToken}><span className="cz-source-label">知乎搜索摘要</span><h3><a href={safeUrl(item.url)} target="_blank" rel="noreferrer">{item.title}<ExternalLink size={13}/></a></h3><p className="cz-muted">{item.author || '作者未提供'}</p><p className="cz-source-summary">{item.summary || '搜索未返回摘要，可前往原链接阅读。'}</p><button className="cz-button cz-small" disabled={addTask.busy || added.has(item.searchResultToken)} onClick={() => addTask.run(() => api(`${circlePath(circle.id)}/sources`, { method: 'POST', json: { searchResultToken: item.searchResultToken } }), () => { setAdded(current => new Set([...current, item.searchResultToken])); onChanged(); notify('资料已加入本轮。', 'success'); })}>{added.has(item.searchResultToken) ? <><Check size={14}/>已加入</> : <><Plus size={14}/>加入本轮资料</>}</button></article>)}</div>}<ErrorNote text={addTask.error}/></>}</div>}
    {!circle.sources.length ? <EmptyState title="资料从一份可靠的出处开始">把帮助你形成观点的文章链接或原文片段放在这里，方便大家继续阅读和核对。</EmptyState> : <div className="cz-source-list">{circle.sources.map(source => <article key={source.id} className="cz-source-card"><div className="cz-source-top"><span className="cz-source-number"><BookOpen size={17}/></span><span className="cz-source-label">{scopeNames[source.scope]}</span>{writable && (source.createdBy === circle.membership?.userId || circle.membership?.role === 'host') && <button className="cz-icon" aria-label={`删除资料：${source.title}`} onClick={() => setRemoving(source)}><Trash2 size={16}/></button>}</div><h3><a href={safeUrl(source.url)} target="_blank" rel="noreferrer">{source.title}<ExternalLink size={15}/></a></h3><p className="cz-source-byline">{source.author || '作者未注明'} · {dateTime(source.createdAt)} 添加</p>{source.summary && <div className="cz-source-summary">{source.summary}</div>}<p className="cz-source-note">{scopeNotes[source.scope]}</p><a className="cz-source-url" href={safeUrl(source.url)} target="_blank" rel="noreferrer"><Link2 size={13}/>{source.url}</a></article>)}</div>}
    {adding && <SourceDialog circleId={circle.id} onClose={() => setAdding(false)} onSaved={() => { setAdding(false); onChanged(); notify('资料已加入本轮。', 'success'); }}/>}
    {removing && <ConfirmDialog title="删除这份资料" buttonText="确认删除" danger onClose={() => setRemoving(null)} onConfirm={async () => { await api(`${circlePath(circle.id)}/sources/${encodeURIComponent(removing.id)}`, { method: 'DELETE' }); onChanged(); }}><p>删除「{removing.title}」后，依赖这份资料的 AI 整理与成果将暂不可见，需要重新整理。</p></ConfirmDialog>}
  </section>;
}

function SourceDialog({ circleId, onClose, onSaved }: { circleId: string; onClose: () => void; onSaved: () => void }) {
  const task = useTask(), [title, setTitle] = useState(''), [url, setUrl] = useState(''), [author, setAuthor] = useState(''), [summary, setSummary] = useState(''), [scope, setScope] = useState<'link' | 'excerpt'>('link');
  return <CircleModal title="添加一份讨论资料" onClose={onClose} busy={task.busy}><form className="cz-form" onSubmit={event => { event.preventDefault(); task.run(() => api(`${circlePath(circleId)}/sources`, { method: 'POST', json: { title: title.trim(), url: url.trim(), author: author.trim(), scope, ...(scope === 'excerpt' ? { summary: summary.trim() } : {}) } }), onSaved); }}>
    <label className="cz-field">资料标题<input autoFocus value={title} onChange={event => setTitle(event.target.value)} required minLength={2} maxLength={200}/></label><label className="cz-field">来源链接<input type="url" value={url} onChange={event => setUrl(event.target.value)} required maxLength={2000} placeholder="https://…"/></label><label className="cz-field">作者 <span>选填</span><input value={author} onChange={event => setAuthor(event.target.value)} maxLength={100}/></label><label className="cz-field">保存方式<select aria-label="保存方式" value={scope} onChange={event => setScope(event.target.value as 'link' | 'excerpt')}><option value="link">仅保存链接</option><option value="excerpt">附上我提供的原文摘录</option></select></label>{scope === 'excerpt' && <label className="cz-field">原文摘录<textarea value={summary} onChange={event => setSummary(event.target.value)} required maxLength={5000} rows={5} placeholder="粘贴与本轮问题有关的原文片段，并保留上下文。"/></label>}<Notice><p>{scopeNotes[scope]}</p></Notice><ErrorNote text={task.error}/><div className="cz-form-actions"><button type="button" className="cz-button" disabled={task.busy} onClick={onClose}>取消</button><SubmitButton busy={task.busy}>添加到本轮</SubmitButton></div>
  </form></CircleModal>;
}

export function CircleOutcomes({ circle, writable, onChanged, onFacilitate, notify }: { circle: CircleDetail; writable: boolean; onChanged: () => void; onFacilitate: () => void; notify: Notify }) {
  const [editor, setEditor] = useState<CircleOutcome | 'new' | null>(null), [historyId, setHistoryId] = useState<string | null>(null), [reviewing, setReviewing] = useState<CircleOutcome | null>(null);
  const exportTask = useTask();
  const editorVisible = editor === 'new' || (editor && circle.outcomes.some(item => item.id === editor.id && !item.redacted));
  const history = circle.outcomes.find(outcome => outcome.id === historyId && !outcome.redacted);
  const reviewVisible = reviewing && circle.outcomes.some(item => item.id === reviewing.id && !item.redacted);
  async function exportOutcome(outcome: CircleOutcome) {
    const response = await fetch(`/api${circlePath(circle.id)}/outcomes/${encodeURIComponent(outcome.id)}/export`, { credentials: 'same-origin', signal: AbortSignal.timeout(30000) });
    if (!response.ok) { const result = await response.json().catch(() => null); throw new Error(result?.error?.message || '成果导出失败，请重试。'); }
    const blob = await response.blob(), url = URL.createObjectURL(blob), link = document.createElement('a');
    link.href = url; link.download = `${outcome.title.replace(/[\\/:*?"<>|]/g, '_').slice(0, 100)}-v${outcome.version}.md`; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section className="cz-outcomes" aria-label="本轮成果"><div className="cz-panel-heading"><div><h2>让答案留得下来</h2><p>整理有依据的发现与行动，区分草稿和成员署名核对的版本。</p></div>{writable && <button className="cz-button cz-primary cz-small" onClick={() => setEditor('new')}><Plus size={15}/>写一份成果</button>}</div>
    {writable && <div className="cz-outcome-helper"><p>需要一个起点？可以先从本轮讨论整理草稿，再逐项核对。</p><button className="cz-text-button" onClick={onFacilitate} disabled={circle.aiStatus.pending}>协助整理草稿<ArrowIcon/></button></div>}
    <ErrorNote text={exportTask.error}/>
    {!circle.outcomes.length ? <EmptyState title="讨论还在发生，成果由大家写下">一份结论清单、一张行动计划，或一段有分歧的发现，都可以成为本轮的成果。</EmptyState> : <div className="cz-outcome-list">{circle.outcomes.map(outcome => <article className="cz-outcome-card" key={outcome.id}><header><span className={`cz-badge ${outcome.status === 'reviewed' ? 'cz-reviewed' : ''}`}>{outcome.status === 'reviewed' ? <><CheckCheck size={13}/>成员已核对</> : '待核对草稿'}</span><span className="cz-muted">v{outcome.version}</span>{outcome.aiMode && <span className="cz-small-badge">{outcome.aiMode === 'model' ? 'AI 辅助整理' : '站内摘录'}</span>}</header><h3>{outcome.title}</h3>{outcome.redacted ? <Notice><p>部分依据已撤回或不可见，这份成果需重新整理。历史版本和导出也会同步保护原内容。</p></Notice> : <><div className="cz-outcome-content">{outcome.content}</div><Citations citations={outcome.citations} sourceIds={outcome.sourceIds} sources={circle.sources}/>{outcome.status === 'reviewed' && <p className="cz-review-signature"><CheckCheck size={15}/>{outcome.reviewedByName || '一位成员'}于 {dateTime(outcome.reviewedAt)} 核对 · 不代表全员共识</p>}<footer><div><button className="cz-text-button" onClick={() => setHistoryId(outcome.id)}><History size={14}/>版本记录</button><button className="cz-text-button" disabled={exportTask.busy} onClick={() => exportTask.run(() => exportOutcome(outcome), () => notify('已导出 Markdown 成果。', 'success'))}><Download size={14}/>导出</button></div>{writable && <div><button className="cz-text-button" onClick={() => setEditor(outcome)}><Pencil size={14}/>编辑</button>{outcome.status !== 'reviewed' && <button className="cz-button cz-small" onClick={() => setReviewing(outcome)}><CheckCheck size={14}/>我已核对</button>}</div>}</footer></>}</article>)}</div>}
    {editor && editorVisible && <OutcomeEditor key={editor === 'new' ? 'new' : editor.id} circle={circle} outcome={editor === 'new' ? undefined : editor} notify={notify} onClose={() => { setEditor(null); onChanged(); }} onSaved={() => { setEditor(null); onChanged(); notify('成果草稿已保存为新版本。', 'success'); }}/>}
    {history && <OutcomeVersionsDialog circleId={circle.id} outcome={history} refreshVersion={circle.updatedAt} onClose={() => setHistoryId(null)}/>}
    {reviewing && reviewVisible && <ConfirmDialog title="以我的名义核对这份成果" buttonText="确认已核对" onClose={() => setReviewing(null)} onConfirm={async () => { await api(`${circlePath(circle.id)}/outcomes/${encodeURIComponent(reviewing.id)}`, { method: 'PATCH', json: { version: reviewing.version, status: 'reviewed' } }); onChanged(); notify('已记录你的核对署名。', 'success'); }}><p>请确认你已检查「{reviewing.title}」的正文与引用依据。本次会记录你的署名，表示你已核对这个版本。</p><p>其他成员仍可提出修改，新编辑会生成待核对版本。</p></ConfirmDialog>}
  </section>;
}

function ArrowIcon() { return <span aria-hidden="true">→</span>; }

function OutcomeVersionsDialog({ circleId, outcome, refreshVersion, onClose }: { circleId: string; outcome: CircleOutcome; refreshVersion: string; onClose: () => void }) {
  const [versions, setVersions] = useState<CircleOutcome[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [retry, setRetry] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError(''); setVersions([]);
    void api<{ versions: CircleOutcome[] }>(`${circlePath(circleId)}/outcomes/${encodeURIComponent(outcome.id)}/versions`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) { setVersions(result.versions); setLoading(false); } }).catch(err => { if (!controller.signal.aborted && !isAbort(err)) { setError(messageOf(err)); setLoading(false); } });
    return () => controller.abort();
  }, [circleId, outcome.id, outcome.version, refreshVersion, retry]);
  return <CircleModal title="成果版本记录" onClose={onClose} wide><div className="cz-form"><p className="cz-form-intro">{outcome.title} · 每次编辑独立保存，旧版本只读。</p>{loading && <Loading/>}<ErrorNote text={error}/>{error && <button className="cz-button cz-small" onClick={() => setRetry(value => value + 1)}>重新加载</button>}{versions.map((version, index) => <details key={version.version} className="cz-version" open={index === 0}><summary>v{version.version} · {version.status === 'reviewed' ? '成员已核对' : '待核对'}<span>{dateTime(version.updatedAt)}</span></summary>{version.redacted ? <p className="cz-muted">这个版本的依据已撤回或不可见，正文不再展示。</p> : <><h3>{version.title}</h3><div className="cz-outcome-content">{version.content}</div>{version.reviewedByName && <p className="cz-muted">由 {version.reviewedByName} 核对</p>}</>}</details>)}<div className="cz-form-actions"><button className="cz-button" onClick={onClose}>关闭</button></div></div></CircleModal>;
}
