import { useEffect, useState } from 'react';
import { Flag, MessageCircle, Settings2, Shield, ShieldOff, UserRoundCheck } from 'lucide-react';
import { api, messageOf } from '../../api';
import { Avatar } from '../../components';
import type { CircleDetail, CircleMember, CircleReport } from '../../../shared/circles-types';
import { circlePath, CircleModal, ConfirmDialog, dateTime, ErrorNote, isAbort, Loading, Notice, SubmitButton, useTask, type Notify } from './CirclesCommon';

export function CircleMembers({ circle, onChanged, onPreferences, onNavigate, onConversation, notify }: { circle: CircleDetail; onChanged: () => void; onPreferences: () => void; onNavigate: (page: string) => void; onConversation?: (id: string) => void; notify: Notify }) {
  const [connecting, setConnecting] = useState<CircleMember | null>(null), [blocking, setBlocking] = useState<CircleMember | null>(null), [moderating, setModerating] = useState(false);
  const host = circle.membership?.role === 'host';
  return <section className="cz-members" aria-label="小组成员"><div className="cz-panel-heading"><div><h2>{circle.memberCount} 位成员，围绕一个问题</h2><p>目标可以相近，经验可以不同。私聊连接需要双方单独同意。</p></div><button className="cz-button cz-small" onClick={onPreferences}><Settings2 size={15}/>我的参与设置</button></div>
    {!circle.membership?.allowConnections && <Notice><UserRoundCheck size={18}/><p>你尚未开放成员连接邀请。可以在参与设置中开启，收到邀请后仍由你确认。</p></Notice>}
    <div className="cz-member-list">{circle.members.map(member => { const own = member.id === circle.membership?.userId; return <article key={member.id} className={`cz-member-card ${member.blocked ? 'cz-member-blocked' : ''}`}><div className="cz-member-info"><Avatar name={member.name} seed={member.id} src={member.avatar || undefined} size={42}/><div><h3>{member.name}{own && <span className="cz-small-badge">我</span>}{member.role === 'host' && <span className="cz-small-badge">主持</span>}{member.blocked && <span className="cz-small-badge">已屏蔽</span>}</h3><p>{member.stage || '尚未填写当前阶段'}</p></div></div><div className="cz-member-goal"><span>本轮期待</span><p>{member.goal || '还没有填写参与目标。'}</p></div><p className="cz-member-expiry">{member.expiresAt ? `参与至 ${dateTime(member.expiresAt)}` : '持续参与'} · {dateTime(member.joinedAt)} 加入</p>{!own && <footer><button className="cz-button cz-small" disabled={!member.canConnect || member.blocked} onClick={() => setConnecting(member)}><MessageCircle size={14}/>邀请连接</button><button className="cz-text-button" onClick={() => setBlocking(member)}>{member.blocked ? <ShieldOff size={14}/> : <Shield size={14}/>} {member.blocked ? '取消屏蔽' : '屏蔽'}</button></footer>}{!own && !member.canConnect && !member.blocked && <p className="cz-invite-hint">双方开放邀请且没有屏蔽时可以连接。</p>}</article>; })}</div>
    {host && <div className="cz-moderator-entry"><Shield size={18}/><div><h3>主持工具</h3><p>核对成员举报，隐藏不合适的发言或保留说明。</p></div><button className="cz-button cz-small" onClick={() => setModerating(true)}><Flag size={14}/>处理举报</button></div>}
    {connecting && circle.members.some(member => member.id === connecting.id && member.canConnect && !member.blocked) && <ConnectionDialog circle={circle} member={connecting} onClose={() => setConnecting(null)} onConnected={conversationId => { setConnecting(null); if (onConversation) onConversation(conversationId); else onNavigate(`connections?conversation=${encodeURIComponent(conversationId)}`); }} notify={notify}/>}
    {blocking && <ConfirmDialog title={blocking.blocked ? '取消屏蔽这位成员' : '屏蔽这位成员'} buttonText={blocking.blocked ? '取消屏蔽' : '确认屏蔽'} danger={!blocking.blocked} onClose={() => setBlocking(null)} onConfirm={async () => { await api(blocking.blocked ? `${circlePath(circle.id)}/blocks/${encodeURIComponent(blocking.id)}` : `${circlePath(circle.id)}/blocks`, { method: blocking.blocked ? 'DELETE' : 'POST', ...(blocking.blocked ? {} : { json: { targetId: blocking.id } }) }); onChanged(); }}><p>{blocking.blocked ? `取消后，你可以重新看到 ${blocking.name} 在小组内可见的内容。` : `屏蔽后，你将不再看到 ${blocking.name} 的发言与资料，双方也不能从本组发起连接。该成员仍留在小组中。`}</p></ConfirmDialog>}
    {moderating && host && <ReportsDialog circleId={circle.id} onClose={() => setModerating(false)} onChanged={onChanged} notify={notify}/>}
  </section>;
}

function ConnectionDialog({ circle, member, onClose, onConnected, notify }: { circle: CircleDetail; member: CircleMember; onClose: () => void; onConnected: (conversationId: string) => void; notify: Notify }) {
  const task = useTask(), [message, setMessage] = useState(`你好，我们都在讨论「${circle.title}」，想继续交流这个问题。`);
  return <CircleModal title={`向 ${member.name} 发出连接邀请`} onClose={onClose} busy={task.busy}><form className="cz-form" onSubmit={event => { event.preventDefault(); task.run(() => api<{ connection: { id: string; status: 'pending' | 'accepted'; conversationId: string | null }; notice: string | null }>(`${circlePath(circle.id)}/connect`, { method: 'POST', json: { targetId: member.id, message: message.trim() } }), result => { if (result.connection.status === 'accepted' && result.connection.conversationId) { notify('双方已确认连接。', 'success'); onConnected(result.connection.conversationId); } else { notify(result.notice || '邀请已发出，对方确认后才能私聊。', 'success'); onClose(); } }); }}>
    <p className="cz-form-intro">说说你想继续交流什么。邀请发送后，需要对方确认才会建立私聊。</p><label className="cz-field">邀请留言<textarea aria-label="邀请留言" autoFocus value={message} onChange={event => setMessage(event.target.value)} required minLength={2} maxLength={500} rows={4}/></label><ErrorNote text={task.error}/><div className="cz-form-actions"><button type="button" className="cz-button" disabled={task.busy} onClick={onClose}>取消</button><SubmitButton busy={task.busy}>发送邀请</SubmitButton></div>
  </form></CircleModal>;
}

function ReportsDialog({ circleId, onClose, onChanged, notify }: { circleId: string; onClose: () => void; onChanged: () => void; notify: Notify }) {
  const [reports, setReports] = useState<CircleReport[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  const task = useTask();
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    void api<{ reports: CircleReport[] }>(`${circlePath(circleId)}/reports`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) { setReports(result.reports); setLoading(false); } }).catch(err => { if (!controller.signal.aborted && !isAbort(err)) { setReports([]); setError(messageOf(err)); setLoading(false); } });
    return () => controller.abort();
  }, [circleId, revision]);
  function resolveReport(report: CircleReport, action: 'hide' | 'dismiss') { task.run(() => api(`${circlePath(circleId)}/reports/${encodeURIComponent(report.id)}/resolve`, { method: 'POST', json: { action } }), () => { setRevision(value => value + 1); onChanged(); notify(action === 'hide' ? '发言已隐藏，举报已处理。' : '已保留发言并结案。', 'success'); }); }
  return <CircleModal title="小组举报处理" onClose={onClose} busy={task.busy} wide><div className="cz-form">{loading && <Loading/>}<ErrorNote text={error}/>{error && <button className="cz-button cz-small" onClick={() => setRevision(value => value + 1)}>重新加载</button>}<ErrorNote text={task.error}/>{!loading && !error && !reports.length && <p className="cz-muted">目前没有成员举报。</p>}{reports.map(report => <article key={report.id} className="cz-report-card"><header><span className="cz-badge">{report.status === 'open' ? '待处理' : report.status === 'hidden' ? '已隐藏发言' : '已保留发言'}</span><time>{dateTime(report.createdAt)}</time></header><p><strong>举报原因：</strong>{report.reason}</p><blockquote>{report.message.authorName}：{report.message.text}</blockquote>{report.status === 'open' && <div className="cz-form-actions"><button className="cz-button cz-small" disabled={task.busy} onClick={() => resolveReport(report, 'dismiss')}>保留发言并结案</button><button className="cz-button cz-small cz-danger" disabled={task.busy} onClick={() => resolveReport(report, 'hide')}>隐藏发言</button></div>}</article>)}<div className="cz-form-actions"><button className="cz-button" disabled={task.busy} onClick={onClose}>关闭</button></div></div></CircleModal>;
}
